/**
 * Photos-app albums. Each photo is a path under public/ without its extension (`rel`);
 * the album grid uses /thumbs/<rel>.jpg and the viewer /view/<rel>.jpg, both generated by
 * `node scripts/make-photo-variants.js` (originals stay where they are).
 * Keep each album in chronological order, oldest → newest.
 */

const mexico = [
	...Array.from({ length: 73 }, (_, i) => ({ rel: `photos/mexico/${String(i + 1).padStart(3, '0')}`, title: 'Mexico' })),
	{ rel: 'photos/mexico/grinch-organillo-night', title: 'Mexico' },
	{ rel: 'photos/mexico/subway-motion-blur', title: 'Mexico' },
	{ rel: 'photos/mexico/feast-mural-staircase-collage', title: 'Mexico' },
	{ rel: 'photos/mexico/frida-hallway-pesos-collage', title: 'Mexico' },
	{ rel: 'photos/mexico/soumaya-david-gallery', title: 'Mexico' },
	{ rel: 'photos/mexico/convenience-store-drinks', title: 'Mexico' },
	{ rel: 'photos/mexico/cathedral-golden-altar', title: 'Mexico' },
	{ rel: 'photos/mexico/angel-lanterns-stickers-collage', title: 'Mexico' },
];

const dayton = [
	{ rel: 'dayton/shark-inflatable-slide', title: 'Shark slide' },
	{ rel: 'dayton/stage-home-lettering-band', title: 'Stage — HOME' },
	{ rel: 'dayton/music-store-acoustic-couch', title: 'Guitar store' },
	{ rel: 'dayton/roof-setup-golden-hour', title: 'Roof load-in' },
	{ rel: 'dayton/snowboard-air-vertical', title: 'Snowboard air' },
	{ rel: 'dayton/band-outdoor-stage-canopy', title: 'Outdoor stage' },
];

const corvallis = [
	{ rel: 'corvallis/band-rehearsal', title: 'Band rehearsal' },
	{ rel: 'corvallis/avocado-toast-acai', title: 'Avocado toast & acai' },
	{ rel: 'corvallis/bowling-scoreboard-lane18', title: 'Bowling — lane 18' },
	{ rel: 'corvallis/tree-canopy-from-below', title: 'Tree canopy' },
	{ rel: 'corvallis/after-hours-tshirt-graphic', title: 'After Hours tee' },
	{ rel: 'corvallis/black-cat-cherry-blossoms', title: 'Cat & blossoms' },
	{ rel: 'corvallis/nintendo-switch-sports-bowling-results', title: 'Switch Sports bowling' },
	{ rel: 'bundled/FineByMe', title: 'Fine By Me' },
];

const eugene = [
	{ rel: 'eugene/living-room-studio-art', title: 'Living room studio' },
	{ rel: 'eugene/tabby-cat-leather-couch', title: 'Tabby on couch' },
	{ rel: 'eugene/lemon-dessert-ice', title: 'Lemon dessert' },
	{ rel: 'eugene/home-music-studio-desk', title: 'Attic desk studio' },
	{ rel: 'eugene/bathtub-guitar-green-tub', title: 'Bathtub jam' },
	{ rel: 'eugene/living-room-yellow-couch-evening', title: 'Evening gathering' },
	{ rel: 'eugene/night-handstand-grass-tree', title: 'Night handstand' },
	{ rel: 'eugene/clownfish-lock-screen-dev-setup', title: 'Lock screen build' },
	{ rel: 'eugene/goodwill-cart-clothes-haul', title: 'Goodwill run' },
	{ rel: 'eugene/car-window-city-night', title: 'City night ride' },
	{ rel: 'eugene/home-pioneer-dj-booth', title: 'Home Pioneer DJ booth' },
	{ rel: 'eugene/mirror-hall-heater-plants', title: 'Hallway mirror & plants' },
	{ rel: 'eugene/portrait-brown-hoodie', title: 'Brown hoodie selfie' },
	{ rel: 'eugene/ableton-live-arrangement', title: 'Ableton arrangement' },
	{ rel: 'eugene/shadows-roll-up-door', title: 'Shadows • roll-up door' },
	{ rel: 'eugene/winter-eugene-tactics-snow', title: 'Snow downtown • Tactics' },
	{ rel: 'eugene/outdoor-photo-shoot-under-bridge', title: 'Shoot under bridge' },
	{ rel: 'bundled/BHDenialSingle', title: 'BH Denial' },
];

const portland = [
	{ rel: 'portland/portland-photo-01', title: 'Portland snapshot 1' },
	{ rel: 'portland/portland-photo-02', title: 'Portland snapshot 2' },
	{ rel: 'portland/portland-photo-03', title: 'Portland snapshot 3' },
	{ rel: 'portland/portland-photo-04', title: 'Portland snapshot 4' },
	{ rel: 'portland/portland-photo-05', title: 'Portland snapshot 5' },
	{ rel: 'portland/portland-photo-06', title: 'Portland snapshot 6' },
	{ rel: 'portland/portland-photo-07', title: 'Portland snapshot 7' },
	{ rel: 'portland/porch-railing-smile', title: 'Porch railing' },
	{ rel: 'portland/park-lawn-summer', title: 'Park lawn' },
	{ rel: 'portland/vintage-horror-posters-rack', title: 'Poster rack' },
	{ rel: 'portland/two-tabby-cats-bed', title: 'Two tabbies' },
	{ rel: 'portland/neon-night-pool-party', title: 'Night pool' },
	{ rel: 'portland/nightclub-led-screens', title: 'LED crowd' },
	{ rel: 'portland/attic-genelec-edit-suite', title: 'Edit suite' },
	{ rel: 'portland/three-friends-parking-lot-sunset', title: 'Parking lot trio' },
	{ rel: 'portland/river-tubes-pickup-day', title: 'Tubes day' },
	{ rel: 'portland/river-wakesurfing', title: 'Wake surf' },
	{ rel: 'portland/car-rear-window-stickers', title: 'Stickered car' },
	{ rel: 'portland/dog-dormer-teal-house', title: 'Dog at the window' },
	{ rel: 'portland/two-friends-interior-ledge', title: 'Interior ledge' },
	{ rel: 'portland/three-polaroids-wood-table', title: 'Polaroids' },
	{ rel: 'portland/csgo-ten-year-veteran-coin', title: 'Ten year coin' },
	{ rel: 'portland/bnw-car-phone-night', title: 'Night ride' },
	{ rel: 'portland/home-studio-green-light', title: 'Green-lit studio' },
	{ rel: 'portland/red-porsche-cherry-blossom-night', title: '911 under blossoms' },
	{ rel: 'portland/kitchen-island-dinner-prep', title: 'Kitchen island' },
	{ rel: 'portland/wetsuit-sunny-selfie', title: 'Sunny selfie' },
	{ rel: 'portland/guitar-studio-through-doorway', title: 'Through the doorway' },
	{ rel: 'portland/grand-piano-waterfront-living', title: 'Piano room' },
	{ rel: 'portland/daw-rehearsal-steakhouse-collage', title: 'Studio collage' },
	{ rel: 'portland/lelas-vietnamese-bistro-outdoor', title: "Lela's Bistro" },
	{ rel: 'portland/six-panel-studio-life-collage', title: 'Day-in-the-life collage' },
	{ rel: 'portland/loft-leopard-rug-office', title: 'Leopard rug loft' },
	{ rel: 'bundled/DriveBlur', title: 'Night blur' },
];

const newYork = [
	{ rel: 'new-york/natural-history-meteorite', title: 'Meteorite hall' },
	{ rel: 'new-york/knockdown-center-marquee', title: 'Knockdown Center' },
	{ rel: 'new-york/manhattan-rooftop-pool-night', title: 'Manhattan night' },
	{ rel: 'new-york/hotel-mirror-selfie', title: 'Hotel mirror' },
	{ rel: 'new-york/moma-gallery-grid', title: 'MoMA' },
	{ rel: 'new-york/broadway-hadestown-stage', title: 'Hadestown' },
];

/** Places, oldest trip first – Camera Roll shows the newest trip first, newest shot first */
const PLACES = [
	{ id: 'dayton', label: 'Dayton', photos: dayton },
	{ id: 'corvallis', label: 'Corvallis', photos: corvallis },
	{ id: 'eugene', label: 'Eugene', photos: eugene },
	{ id: 'portland', label: 'Portland', photos: portland },
	{ id: 'new-york', label: 'New York', photos: newYork },
	{ id: 'mexico', label: 'Mexico', photos: mexico },
];

const cameraRoll = (() => {
	const seen = new Set();
	return [...PLACES]
		.reverse()
		.flatMap((p) => [...p.photos].reverse())
		.filter((p) => (seen.has(p.rel) ? false : (seen.add(p.rel), true)));
})();

/** Album list order: Camera Roll, then places newest trip first */
export const ALBUMS = [
	{ id: 'camera-roll', label: 'Camera Roll', photos: cameraRoll },
	...[...PLACES].reverse(),
];

export const thumbSrc = (photo) => `/thumbs/${photo.rel}.jpg`;
export const viewSrc = (photo) => `/view/${photo.rel}.jpg`;
